version: "3"

services:

  db:
    image: postgres:12
    env_file:
      - ./web/exchange_system.env
    ports:
      - "5432:5432"

  web:
    build: ./web
    links:
      - db
    expose:
      - "8000"
    volumes:
      - ./web:/app
      - ./web/config/sv/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - ./web/exchange_system.env:/etc/environment
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./web/static:/app/static
      - ./web/config/nginx:/etc/nginx/conf.d
    depends_on:
      - web